const curiosityTopics = [
  'the northern lights',
  'ancient libraries',
  'how bees communicate',
  'deep sea creatures',
  'the history of maps',
  'volcanic islands',
  'the science of sleep',
  'forgotten inventions',
  'the origin of language',
  'desert ecosystems',
  'the mathematics of music',
  'the oldest trees',
  'how bridges work',
  'the history of chocolate',
  'cloud formations',
  'the psychology of curiosity',
  'underwater archaeology',
  'the evolution of birds',
  'how memory works',
  'rare weather events',
  'the history of bicycles',
  'coral reef ecosystems',
  'the science of bread',
  'ancient navigation',
  'how earthquakes happen',
  'the lives of octopuses',
  'the history of clocks',
  'why leaves change color',
  'the art of origami',
  'the invention of photography',
  'how ants build colonies',
  'the history of tea',
  'the physics of rainbows',
  'forgotten cities',
  'the science of fermentation',
  'how birds migrate',
  'the history of punctuation',
  'the architecture of caves',
  'how magnets work',
  'the origins of board games',
  'the science of fingerprints',
  'the history of umbrellas',
  'how glaciers move',
  'the language of dolphins',
  'the history of printing',
  'why cats purr',
  'the science of camouflage',
  'ancient cooking methods',
  'how rivers form',
  'the history of calendars',
  'the biology of mushrooms',
  'how elevators work',
  'the story of paper',
  'the science of laughter',
  'lost works of art',
  'how seeds travel',
  'the history of keys',
  'the physics of sound',
  'the lives of urban foxes',
  'how satellites stay in orbit',
  'the history of mirrors',
  'the science of taste',
  'ancient medical practices',
  'how spiders make webs',
  'the history of lighthouses',
  'the chemistry of color',
  'why birds sing',
  'the origins of surnames',
  'how wind turbines work',
  'the science of pollen',
  'the lives of desert animals',
  'how compasses work',
  'the history of theater',
  'the physics of bubbles',
  'ancient trade routes',
  'how trees communicate',
  'the history of buttons',
  'the science of balance',
  'why oceans have tides',
  'the origins of written numbers',
  'how solar panels work',
  'the history of playgrounds',
  'the biology of butterflies',
  'how sound travels',
  'the history of recipes',
  'the science of honey',
  'forgotten languages',
  'how tunnels are built',
  'the history of postcards',
  'the physics of flight',
  'why whales sing',
  'the origins of musical instruments',
  'how weather forecasts work',
  'the science of soil',
  'ancient building techniques',
  'how fireflies glow',
  'the history of nicknames',
  'the biology of forests',
  'how cameras focus',
  'the history of public parks'
];

const curiosityPatterns = [
  'What is {topic}?',
  'How does {topic} work?',
  'Why is {topic} interesting?',
  'A beginner guide to {topic}',
  'The history of {topic}',
  'The science behind {topic}',
  'Surprising facts about {topic}',
  'The latest research on {topic}',
  'The most unusual examples of {topic}',
  'How {topic} has changed over time'
];

const curiousWords = curiosityTopics.flatMap(topic =>
  curiosityPatterns.map(pattern => pattern.replace('{topic}', topic))
);
